# This workflow will build an iOS project for iPhone 12 Pro on iOS 18.4
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build for iPhone 12 Pro (iOS 18.4)
        run: |
          xcodebuild build -project ios-pwnagotchi.xcodeproj \
            -scheme "ios-pwnagotchi" \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=18.4" \
            -configuration Debug \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Run tests
        run: |
          xcodebuild test -project ios-pwnagotchi.xcodeproj \
            -scheme "ios-pwnagotchi" \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=18.4" \
            -configuration Debug \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty
