# This workflow will build an iOS project for iPhone 12 Pro on iOS 18.4 and export an IPA
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: iOS Build for iPhone 12 Pro (iOS 18.4)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: macos-14 # Using macOS 14 (Sonoma) for latest iOS support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build for iPhone 12 Pro (iOS 18.4)
        run: |
          xcodebuild clean build -project ios-pwnagotchi.xcodeproj \
            -scheme "ios-pwnagotchi" \
            -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=18.4" \
            -configuration Release \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

      - name: Archive and Export IPA
        run: |
          # Create a temporary keychain
          KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain
          KEYCHAIN_PASSWORD=temporary

          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -t 3600 -u "$KEYCHAIN_PATH"

          # Create an archive
          mkdir -p build/archive
          xcodebuild archive \
            -project ios-pwnagotchi.xcodeproj \
            -scheme "ios-pwnagotchi" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -sdk iphoneos \
            -archivePath build/archive/ios-pwnagotchi.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          # Create export options plist
          cat > exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>teamID</key>
              <string></string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOL

          # Export IPA (this might fail due to signing issues in CI)
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath build/archive/ios-pwnagotchi.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist \
            || echo "IPA export failed, trying alternate method"

          # Alternative method if export fails due to signing
          if [ ! -f build/ipa/ios-pwnagotchi.ipa ]; then
            echo "Using alternate IPA generation method"
            cd build/archive/ios-pwnagotchi.xcarchive/Products/Applications
            mkdir -p Payload
            cp -R *.app Payload/
            zip -r ios-pwnagotchi.ipa Payload
            mkdir -p ../../../../ipa/
            mv ios-pwnagotchi.ipa ../../../../ipa/
          fi

          # Clean up
          security delete-keychain "$KEYCHAIN_PATH"

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-pwnagotchi-iPhone12Pro-iOS18.4
          path: build/ipa/*.ipa
          if-no-files-found: error
